/*
 * m4a2s is aprogram to to dump sound files from m4a/mp2k GBA games to pseudo-assembly source files
 * Copyright (C) 2015 ipatix
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 */

using System.Collections;
using System.IO;
using System.Text;

namespace m4a2s
{
    class Songtable
    {
        public static void disassemble(Hashtable index, string destFile)
        {
            StringBuilder oasm = new StringBuilder();

            oasm.AppendLine("@ File generated by m4a2s Songtable-Module");

            oasm.AppendLine("\t.section .rodata");
            oasm.AppendLine(".global\t_songtable");
            oasm.AppendLine("\t.align\t2");
            oasm.AppendLine();
            oasm.AppendLine("_songtable:");
            oasm.AppendLine();

            for (int i = 0; i < Rom.NumSongs; i++)
            {
                Rom.Reader.BaseStream.Position = Rom.SongtableOffset + (i*8);
                oasm.AppendLine("@**************** Song " + i.ToString("D4") + " ****************@");
                oasm.AppendLine();
                oasm.AppendLine("\t.word\t" + ((Entity)index[Rom.Reader.ReadInt32() - Rom.Map]).Guid);
                oasm.AppendLine("\t.byte\t0x" + Rom.Reader.ReadByte().ToString("X2") + ", 0x" +
                                Rom.Reader.ReadByte().ToString("X2") + ", 0x" + Rom.Reader.ReadByte().ToString("X2") +
                                ", 0x" + Rom.Reader.ReadByte().ToString("X2"));
                oasm.AppendLine();
            }

            oasm.AppendLine("\t.end");

            File.WriteAllText(destFile, oasm.ToString());
        }
    }
}
