using System.Collections;
using System.IO;
using System.Text;

namespace m4a2s
{
    class Songtable
    {
        public static void disassemble(Hashtable index, string destFile)
        {
            StringBuilder oasm = new StringBuilder();

            oasm.AppendLine("@ File generated by m4a2s Songtable-Module");

            oasm.AppendLine("\t.section .rodata");
            oasm.AppendLine(".global\t_songtable");
            oasm.AppendLine("\t.align\t2");
            oasm.AppendLine();
            oasm.AppendLine("_songtable:");
            oasm.AppendLine();

            for (int i = 0; i < Rom.NumSongs; i++)
            {
                Rom.Reader.BaseStream.Position = Rom.SongtableOffset + (i*8);
                oasm.AppendLine("@**************** Song " + i.ToString("D4") + " ****************@");
                oasm.AppendLine();
                oasm.AppendLine("\t.word\t" + ((Entity)index[Rom.Reader.ReadInt32() - Rom.Map]).Guid);
                oasm.AppendLine("\t.byte\t0x" + Rom.Reader.ReadByte().ToString("X2") + ", 0x" +
                                Rom.Reader.ReadByte().ToString("X2") + ", 0x" + Rom.Reader.ReadByte().ToString("X2") +
                                ", 0x" + Rom.Reader.ReadByte().ToString("X2"));
                oasm.AppendLine();
            }

            oasm.AppendLine("\t.end");

            File.WriteAllText(destFile, oasm.ToString());
        }
    }
}
